# Generated by Django 5.1.1 on 2024-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_record_address_remove_record_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
