# Generated by Django 5.1.1 on 2024-10-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_record_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='Record',
        ),
    ]
